/**
 *  @author Freddy Wordingham
 *  @email  fjmw201@exeter.ac.uk
 *
 *  @date   25/01/2018.
 */



//  == GUARD ==
#ifndef ARCTORUS_SRC_CLS_RANDOM_UNIFORM_HPP
#define ARCTORUS_SRC_CLS_RANDOM_UNIFORM_HPP



//  == INCLUDES ==
//  -- System --
#include <cstdint>



//  == NAMESPACE ==
namespace arc
{
    namespace random
    {



        //  == CLASS ==
        /**
         *  A sudo-random number generator capable of producing sudo random numbers with uniform probability.
         *  Primarily used to generate random doubles between zero and unity.
         */
        class Uniform
        {
            //  == TYPE DEFINITIONS ==
          private:
            //  -- Generation --
            using base = uint64_t;  //! Base type generated by this class.


            //  == FIELDS ==
          private:
            //  -- Seed --
            const base m_seed;  //! Seed used to initialise the generator.

            //  -- Generation Variables --
            base m_u;   //! First value used in the generation of random values.
            base m_v;   //! Second value used in the generation of random values.
            base m_w;   //! Third value used in the generation of random values.


            //  == INSTANTIATION ==
          public:
            //  -- Singleton --
            static Uniform& get_instance(const base t_seed = 0);

          private:
            //  -- Constructors --
            Uniform(const base t_seed);

            //  -- Initialisation --
            void init_genaration_variables();


            //  == OPERATORS ==
          private:


            //  == METHODS ==
          private:
            //  -- Generation --
            base gen_base();
        };



    } // namespace random
} // namespace arc



//  == GUARD END ==
#endif // ARCTORUS_SRC_CLS_RANDOM_UNIFORM_HPP
